trainingInput:
  scaleTier: BASIC
  runtimeVersion: '1.7'
  pythonVersion: '2.7'
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: RMSELOSS
    maxTrials: 4
    maxParallelTrials: 1
    enableTrialEarlyStopping: True
    params: 
    - parameterName: scale_factor
      type: DOUBLE
      minValue: 0.1
      maxValue: 0.9
      scaleType: UNIT_LINEAR_SCALE 
    - parameterName: first_hidden_units
      type: INTEGER
      minValue: 16
      maxValue: 2048
      scaleType: UNIT_LINEAR_SCALE